//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilgi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id_a { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Id_a_e { get; set; }
        public Nullable<int> Id_a_v { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
