//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilgi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor_Appointment
    {
        public int Id_v_a { get; set; }
        public string Service { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Type { get; set; }
        public Nullable<int> Id_v_a_v { get; set; }
        public string Email { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
